// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'FioWiki',
    },

    {
      type: 'category',
      label: 'Config',
      collapsible: true,
      collapsed: true,
      items: ['config/coming-soon'],
    },

    {
      type: 'category',
      label: 'Plugin',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'FioChatGames',
          collapsible: true,
          collapsed: true,
          items: [
            'plugin/fiochatgames/index',
            'plugin/fiochatgames/actions',
            'plugin/fiochatgames/commands-permissions',
            'plugin/fiochatgames/api',
            'plugin/fiochatgames/options',
            'plugin/fiochatgames/placeholders',
            {
              type: 'category',
              label: 'Configuration',
              items: [
                'plugin/fiochatgames/config/lang',
                'plugin/fiochatgames/config/config.yml',
                'plugin/fiochatgames/config/item_en.json',
              ],
            },
            {
              type: 'category',
              label: 'Events',
              items: [
                'plugin/fiochatgames/config/events/explanation',
                'plugin/fiochatgames/config/events/fast_type',
                'plugin/fiochatgames/config/events/fillout',
                'plugin/fiochatgames/config/events/guesstheword',
                'plugin/fiochatgames/config/events/guess_the_number',
                'plugin/fiochatgames/config/events/math',
                'plugin/fiochatgames/config/events/roman',
                'plugin/fiochatgames/config/events/random',
                'plugin/fiochatgames/config/events/reaction',
                'plugin/fiochatgames/config/events/rewrite',
                'plugin/fiochatgames/config/events/trivia',
                'plugin/fiochatgames/config/events/unreverse',
                'plugin/fiochatgames/config/events/unscramble',
                'plugin/fiochatgames/config/events/unshuffle',
                'plugin/fiochatgames/config/events/variable',
              ],
            },
            {
              type: 'category',
              label: 'Races',
              items: [
                'plugin/fiochatgames/config/races/explanation',
                'plugin/fiochatgames/config/races/bartering_race',
                'plugin/fiochatgames/config/races/break_race',
                'plugin/fiochatgames/config/races/breeding_race',
                'plugin/fiochatgames/config/races/brewing_race',
                'plugin/fiochatgames/config/races/brush_race',
                'plugin/fiochatgames/config/races/carve_pumpkin_race',
                'plugin/fiochatgames/config/races/composting_race',
                'plugin/fiochatgames/config/races/consume_race',
                'plugin/fiochatgames/config/races/craft_race',
                'plugin/fiochatgames/config/races/curing_race',
                'plugin/fiochatgames/config/races/deal_damage_race',
                'plugin/fiochatgames/config/races/enchant_race',
                'plugin/fiochatgames/config/races/exp_levels_race',
                'plugin/fiochatgames/config/races/exp_points_race',
                'plugin/fiochatgames/config/races/fishing_race',
                'plugin/fiochatgames/config/races/harvest_race',
                'plugin/fiochatgames/config/races/hatching_race',
                'plugin/fiochatgames/config/races/hunt_race',
                'plugin/fiochatgames/config/races/item_breaking_race',
                'plugin/fiochatgames/config/races/item_damage_race',
                'plugin/fiochatgames/config/races/item_mending_race',
                'plugin/fiochatgames/config/races/milking_race',
                'plugin/fiochatgames/config/races/obtain_items_race',
                'plugin/fiochatgames/config/races/place_race',
                'plugin/fiochatgames/config/races/placeholderapi_race',
                'plugin/fiochatgames/config/races/player_death_race',
                'plugin/fiochatgames/config/races/player_kills_race',
                'plugin/fiochatgames/config/races/projectile_launching_race',
                'plugin/fiochatgames/config/races/resurrecting_race',
                'plugin/fiochatgames/config/races/shear_race',
                'plugin/fiochatgames/config/races/shoot_at_entity',
                'plugin/fiochatgames/config/races/smelt_race',
                'plugin/fiochatgames/config/races/smithing_race',
                'plugin/fiochatgames/config/races/spy_entity_race',
                'plugin/fiochatgames/config/races/stand_on_race',
                'plugin/fiochatgames/config/races/stripping_race',
                'plugin/fiochatgames/config/races/taming_race',
                'plugin/fiochatgames/config/races/trading_race',
                'plugin/fiochatgames/config/races/walking_race',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'FioBlackMarket',
          collapsible: true,
          collapsed: true,
          items: [
            'plugin/fioblackmarket/index',
            'plugin/fioblackmarket/commands-permissions',
            'plugin/fioblackmarket/api',
            'plugin/fioblackmarket/config',
            'plugin/fioblackmarket/blackmarkets',
            'plugin/fioblackmarket/menus',
            'plugin/fioblackmarket/hologram',
            'plugin/fioblackmarket/npc',
          ],
        },
        {
          type: 'category',
          label: 'FioVoucher',
          collapsible: true,
          collapsed: true,
          items: [
            'plugin/fiovoucher/index',
            'plugin/fiovoucher/commands-permissions',
            'plugin/fiovoucher/config',
            {
              type: 'category',
              label: 'Vouchers',
              collapsible: true,
              collapsed: true,
              items: [
                'plugin/fiovoucher/vouchers/how-to-create',
                'plugin/fiovoucher/vouchers/material',
                'plugin/fiovoucher/vouchers/flags',
                'plugin/fiovoucher/vouchers/lore',
                'plugin/fiovoucher/vouchers/shadow',
                'plugin/fiovoucher/vouchers/gradients',
                'plugin/fiovoucher/vouchers/minimessage',
                'plugin/fiovoucher/vouchers/commands',
                'plugin/fiovoucher/vouchers/actions',
                'plugin/fiovoucher/vouchers/settings',
                'plugin/fiovoucher/vouchers/trials-rank-example',
                'plugin/fiovoucher/vouchers/permission-example',
                'plugin/fiovoucher/vouchers/item-example',
                'plugin/fiovoucher/vouchers/example',
              ],
            },
            'plugin/fiovoucher/menu',
            'plugin/fiovoucher/api',
          ],
        },
        {
          type: 'category',
          label: 'FioChat',
          collapsible: true,
          collapsed: true,
          items: [
            'plugin/fiochat/index',
            'plugin/fiochat/actions',
            'plugin/fiochat/commands-permissions',
            'plugin/fiochat/api',
            'plugin/fiochat/options',
            'plugin/fiochat/placeholders',
            {
              type: 'category',
              label: 'Modules',
              items: [
                {
                  type: 'category',
                  label: 'Alerts',
                  items: [
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/giveaway',
                      label: 'Giveaway',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/inventory-full-alert',
                      label: 'Inventory Full Alert',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/server-auto-restart',
                      label: 'Server Auto Restart',
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'Announce',
                  items: [
                    {
                      type: 'category',
                      label: 'Advancements',
                      items: [
                        'plugin/fiochat/modules/announce/advancements/advancements-config',
                        'plugin/fiochat/modules/announce/advancements/advancements-json',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Away from Keyboard',
                      items: [
                        'plugin/fiochat/modules/announce/away-from-keyboard/afk-config',
                        'plugin/fiochat/modules/announce/away-from-keyboard/afk-history-gui',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Biome Discovery',
                      items: [
                        'plugin/fiochat/modules/announce/biome-discovery/config',
                        'plugin/fiochat/modules/announce/biome-discovery/biome-json',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Custom Death Msg',
                      items: [
                        'plugin/fiochat/modules/announce/custom-death-msg/config',
                        'plugin/fiochat/modules/announce/custom-death-msg/custom-death-messages',
                        'plugin/fiochat/modules/announce/custom-death-msg/items-en-json',
                        'plugin/fiochat/modules/announce/custom-death-msg/mobs-en-json',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Custom Join Quit Msg',
                      items: [
                        'plugin/fiochat/modules/announce/custom-join-quit-msg/config',
                        'plugin/fiochat/modules/announce/custom-join-quit-msg/styles',
                        'plugin/fiochat/modules/announce/custom-join-quit-msg/sound',
                        'plugin/fiochat/modules/announce/custom-join-quit-msg/particles',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Day Counter',
                      items: [
                        'plugin/fiochat/modules/announce/day-counter/config',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Mailbox',
                      items: [
                        'plugin/fiochat/modules/announce/mailbox/config',
                        'plugin/fiochat/modules/announce/mailbox/inbox-gui',
                        'plugin/fiochat/modules/announce/mailbox/compose-gui',
                        'plugin/fiochat/modules/announce/mailbox/history-gui',
                        'plugin/fiochat/modules/announce/mailbox/view-gui',
                        'plugin/fiochat/modules/announce/mailbox/sent-gui',
                        'plugin/fiochat/modules/announce/mailbox/rewards-gui',
                        'plugin/fiochat/modules/announce/mailbox/selector-gui',
                        'plugin/fiochat/modules/announce/mailbox/delete-confirm-gui',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Message of the Day',
                      items: [
                        'plugin/fiochat/modules/announce/message-of-the-day/motd',
                        'plugin/fiochat/modules/announce/message-of-the-day/placeholder',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Mute Chat',
                      items: [
                        'plugin/fiochat/modules/announce/mute-chat/config',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Server Announcements',
                      items: [
                        'plugin/fiochat/modules/announce/server-announcements/announce-config',
                        'plugin/fiochat/modules/announce/server-announcements/placeholder-config',
                        'plugin/fiochat/modules/announce/server-announcements/warning-config',
                        'plugin/fiochat/modules/announce/server-announcements/broadcast-config',
                        'plugin/fiochat/modules/announce/server-announcements/alerts-config',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Welcome UI',
                      items: [
                        'plugin/fiochat/modules/announce/welcome-ui/config',
                      ],
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'Chat',
                  items: [
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/auto-reply',
                      label: 'Bot Replying',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/chat-channels',
                      label: 'Chat Channels',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/formats',
                      label: 'Chat Formats',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/chat-history',
                      label: 'Chat History',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/per-world-chat',
                      label: 'Chat Per World',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/chat-radius',
                      label: 'Chat Radius',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/custom-font',
                      label: 'Custom Fonts',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/emojis',
                      label: 'Emojis',
                    },
                    {
                      type: 'category',
                      label: 'Moderations',
                      items: [
                        'plugin/fiochat/modules/chat-management-cooldown',
                        'plugin/fiochat/modules/chat-management-flood',
                        'plugin/fiochat/modules/chat-management-antiunicode',
                        'plugin/fiochat/modules/chat-management-antibot',
                        'plugin/fiochat/modules/chat-management-antirepeat',
                        'plugin/fiochat/modules/chat-management-warn-points',
                        'plugin/fiochat/modules/chat-management-grammar',
                        'plugin/fiochat/modules/chat-management-anti-caps',
                        'plugin/fiochat/modules/chat-management-clear-chat',
                        'plugin/fiochat/modules/chat-management-antiswear',
                        'plugin/fiochat/modules/chat-management-anti-adv',
                        'plugin/fiochat/modules/chat-management-alert-spy',
                      ],
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/mentions',
                      label: 'Player Mentions',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/replying-message',
                      label: 'Player Reply Msg',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/messages',
                      label: 'Private Message',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/quickchat',
                      label: 'QuickChat',
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'Commands',
                  items: [
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/command-hider',
                      label: 'Commands Hider',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/commands-schedule',
                      label: 'Commands Scheduler',
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'Display',
                  items: [
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/inventory-see',
                      label: 'Inventory See',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/item-displays',
                      label: 'Item Display',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/itemtag',
                      label: 'Item Drop Tag',
                    },
                    {
                      type: 'category',
                      label: 'Regions',
                      items: [
                        'plugin/fiochat/modules/regions/music',
                        'plugin/fiochat/modules/regions/particle',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Server Display Tag',
                      items: [
                        'plugin/fiochat/modules/display-tag-animations',
                        'plugin/fiochat/modules/display-tag-scoreboard',
                        'plugin/fiochat/modules/display-tag-bossbar',
                        'plugin/fiochat/modules/display-tag-gamertag',
                        'plugin/fiochat/modules/display-tag-tab',
                      ],
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'Moderations',
                  items: [
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/reports',
                      label: 'Player Reports',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/player-motd',
                      label: 'Server Message of the Day',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/vanish',
                      label: 'Vanish',
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'Rewards',
                  items: [
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/login-streak-rewards',
                      label: 'Login Streak Rewards',
                    },
                    {
                      type: 'doc',
                      id: 'plugin/fiochat/modules/redeem-code',
                      label: 'Redeem Code',
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'FioMenu',
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'plugin/fiomenu',
            },
          ],
        },
        {
          type: 'category',
          label: 'FioTags',
          collapsible: true,
          collapsed: true,
          items: [
            'plugin/fiotags/index',
            'plugin/fiotags/commands-permissions',
            'plugin/fiotags/options',
            'plugin/fiotags/placeholders',
            'plugin/fiotags/api',
            'plugin/fiotags/features',
            {
              type: 'category',
              label: 'Menu',
              collapsible: true,
              collapsed: true,
              items: [
                'plugin/fiotags/menu/menu',
                'plugin/fiotags/menu/settings',
                'plugin/fiotags/menu/custom-tag-history',
                {
                  type: 'category',
                  label: 'Admin Menu',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'plugin/fiotags/menu/admin/dashboard',
                    'plugin/fiotags/menu/admin/tag-list',
                    'plugin/fiotags/menu/admin/tag-editor',
                    'plugin/fiotags/menu/admin/tag-category',
                    'plugin/fiotags/menu/admin/section-editor',
                    'plugin/fiotags/menu/admin/preview-settings',
                    'plugin/fiotags/menu/admin/placeholder-list',
                    'plugin/fiotags/menu/admin/permission-list',
                    'plugin/fiotags/menu/admin/material-selector',
                    'plugin/fiotags/menu/admin/list-editor',
                    'plugin/fiotags/menu/admin/language',
                    'plugin/fiotags/menu/admin/item-flag-selector',
                    'plugin/fiotags/menu/admin/field-editor',
                    'plugin/fiotags/menu/admin/equipped-tag-sync',
                    'plugin/fiotags/menu/admin/custom-item-editor',
                    'plugin/fiotags/menu/admin/create',
                    'plugin/fiotags/menu/admin/create-section',
                    'plugin/fiotags/menu/admin/create-category',
                    'plugin/fiotags/menu/admin/command-aliases',
                    'plugin/fiotags/menu/admin/command-aliases-category',
                    'plugin/fiotags/menu/admin/update-settings',
                  ],
                },
              ],
            },
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Setup',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Sawit',
          collapsible: true,
          collapsed: true,
          items: [
            'setup/sawit/overview',
            'setup/sawit/plugins',
            'setup/sawit/explanation',
            {
              type: 'category',
              label: 'Features',
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: 'category',
                  label: 'Ranks',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'setup/sawit/features/ranks/staff',
                    'setup/sawit/features/ranks/media',
                    'setup/sawit/features/ranks/premium',
                    'setup/sawit/features/ranks/upgrade',
                  ],
                },
                'setup/sawit/features/leaderboards',
                'setup/sawit/features/worlds',
                'setup/sawit/features/datapacks',
              ],
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
